### ISSUE TITLE
Add more social profiles in the website

### ISSUE THREAD

**Issue by achiv** [fossasia/sciencehack-artwork#1]
@mariobehling 
The website has a link to twitter and facebook profiles. I intend to add links to "Github repo" and "Instagram Tags" (#sciencehackday) in a way that is similar to the links provided in the <a href ="https://2018.fossasia.org/">Foss Asia Website</a>. 

![insta_shd](https://user-images.githubusercontent.com/16984674/34140490-12d8aaf0-e4a1-11e7-856d-ce52436a28af.png)

![science_hack_asia](https://user-images.githubusercontent.com/16984674/34140497-1a09249e-e4a1-11e7-8dda-545f02dc6e86.png)

**Comment by ayushjain01** [comment]
Hii! 
Is the issue still open?
Can I work on it?
